
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wxrwuijnhyovicqkypzi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind4cnd1aWpuaHlvdmljcWt5cHppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1NDUzMDEsImV4cCI6MjA1ODEyMTMwMX0.-lasnW35qVfTEJgtwX9EmOueuRHAQPed3ltprgbILmU";
const SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind4cnd1aWpuaHlvdmljcWt5cHppIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0MjU0NTMwMSwiZXhwIjoyMDU4MTIxMzAxfQ.O-PSp1wCvzOcxhGxBV-vV71rpH8ULrU97Y1bBOGDuGQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create client with the publishable key (for regular operations)
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true
  }
});

// Create a client with the service role key for admin operations
// Only use this for server-side operations that require extended permissions
export const supabaseAdmin = createClient<Database>(SUPABASE_URL, SERVICE_ROLE_KEY, {
  auth: {
    autoRefreshToken: false,
    persistSession: false
  }
});

// Export admin.auth for compatibility
supabase.auth.admin = supabaseAdmin.auth.admin;
